@server = http://localhost:8080


//근데 요청할때 왜 ""로 안감쌈?
//쿼리스트링은 문자로 자동보내지는건가
//성별 int 로 클라이언트가 입력했을 때 스트링으로 바꾸는 법?
POST {{server}}/users
Content-Type: application/x-www-form-urlencoded 

name= 요
&age=3
&gender=0
&job=응가

###
GET http://localhost:8080/users

###
DELETE  http://localhost:8080/users/10

###
PUT {{server}}/edit/0
Content-Type: application/x-www-form-urlencoded 

name=응아
&age=28
&gender=0
&job=개발자 선생님

###
GET http://localhost:8080/get

###
PUT {{server}}/getEditUser/1
Content-Type: application/x-www-form-urlencoded 



###
POST {{server}}/edit
Content-Type: application/x-www-form-urlencoded 

name=응아
&age=28
&gender=0
&job=개발자 선생님